### PR TITLE
feat: update incubations based on biblio.js (closes #3)

### LINKED ISSUE #3: List of repos should auto update
The list on the front page should automatically update. We can use the GH API for that: 
https://api.github.com/orgs/wicg/repos

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by marcoscaceres — COMMENTED** [review]
Merging so we can move forward.

**Comment by marcoscaceres** [comment]
Will deploy soon

**Comment by cwilso** [comment]
Sweeeet!  Thanks Marcos!

**Comment by marcoscaceres** [comment]
np, deployed

**Pull request merged**
